nicks_to_paths = {
    'plex_tools': "media_server.plex.plex_tools",
    'plex_manager': "media_server.plex.plex_manager",
    'jellyfin': 'media_server.jellyfin.jellyfin',
    'jellyfin_manager': "media_server.jellyfin.jellyfin_manager",
    'emby_manager': "media_server.emby.emby_manager",
    'olaris_manager': "media_server.olaris.olaris_manager",
    'upgrade_chat': "discord_cogs.upgradeChat.upgrade_chat",
    'booksonic': "media_server.booksonic.booksonic",
    'rclone': "media_server.rclone.rclone",
    'news': "news.news",
    'marta': "MARTA.marta",
    'roles': "discord_cogs.roles",
    'espn': "sports.espn.espn",
    'yahoo_fantasy': "sports.yahoofantasy.yahoofantasy",
    'sengled': "smart_home.sengled_lights.sengled",
    'google_home': "smart_home.google_home.google_home",
    'wink': "smart_home.wink.wink",
    'coronavirus': "general.coronavirus",
    'speedtest': "general.speedtest",
    'voice_channel': "voice.__init__"
}
