CREATE USER 'DiscordBot'@'%' IDENTIFIED BY 'DiscordBot';
CREATE DATABASE PlexDiscord;
USE PlexDiscord;
CREATE TABLE users (DiscordID BIGINT, PlexUsername VARCHAR(100), PlexEmail VARCHAR(100), ExpirationStamp INT, Note VARCHAR(5));
GRANT ALL PRIVILEGES ON PlexDiscord.* TO 'DiscordBot'@'%' IDENTIFIED BY 'DiscordBot' WITH GRANT OPTION;
CREATE DATABASE EmbyDiscord;
USE EmbyDiscord;
CREATE TABLE users (DiscordID BIGINT, EmbyUsername VARCHAR(100), EmbyID VARCHAR(100), ExpirationStamp INT, Note VARCHAR(5));
GRANT ALL PRIVILEGES ON EmbyDiscord.* TO 'DiscordBot'@'%' IDENTIFIED BY 'DiscordBot' WITH GRANT OPTION;
CREATE DATABASE JellyfinDiscord;
USE JellyfinDiscord;
CREATE TABLE users (DiscordID BIGINT, JellyfinUsername VARCHAR(100), JellyfinID VARCHAR(100), ExpirationStamp INT, Note VARCHAR(5));
GRANT ALL PRIVILEGES ON JellyfinDiscord.* TO 'DiscordBot'@'%' IDENTIFIED BY 'DiscordBot' WITH GRANT OPTION;
